### ISSUE TITLE
Local Scene

### ISSUE THREAD

**Issue by tin2tin** [K-410/blender-scripts#1]
When running Local Scene I get this error:
![image](https://user-images.githubusercontent.com/1322593/59972290-b10ead80-958c-11e9-9c15-1430c5e20982.png)

I'm a bit curious it this add-on can be used as a workaround for the current limitation in the Sequencer where scene strips can't be added from the same scene as the Sequencer is located in?

**Comment by K-410** [comment]
I'm not familiar about the sequencer and the limitation you describe.

This addon was a proof of concept during the period when blender still was lacking local view, and doesn't really serve much purpose anymore. Only reason I left it here is because it was one of the first addons I wrote :P

There was an api change where ``scene.update()`` was changed to ``view_layer.update()``. Should be fixed now.
